obj-$(CONFIG_MSM_VIDC_V4L2) :=  msm_smem.o \
				msm_vidc_debug.o \
				msm_vidc_res_parse.o \
				venus_hfi.o \
				hfi_response_handler.o \
				hfi_packetization.o \
				vidc_hfi.o \
				q6_hfi.o \
